---
- hosts: "{{ servers }}"
  tasks:
  - name: Start iperf3 Server
    shell: iperf3 --server --port {{ s_port }} --one-off --daemon
- hosts: "{{ clients }}"
  tasks:
  - name: Start iperf3 client
    shell: "iperf3 --client {{ servers }} --port {{ s_port }} --bitrate {{ bandwidth }} --time {{ duration }} --cport {{ c_port }} --parallel {{ num_conn }} {{ udp_option }} >> iperf_results.out"
  - name: Grab iperf3 Output
    fetch: src=iperf_results.out dest=results/ flat=yes
  - name: Archieve test results
    shell: "mkdir -p iperf-test-archieve && mv iperf_results.out iperf-test-archieve/iperf_results.out"

- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Sender
    tags: sender
    shell: "tail -4 results/iperf*.out | awk '/sender/ {sum+=$6} END { print sum }'"
    register: sender
  - name: Receiver
    tags: receiver
    shell: "tail -4 results/iperf*.out | awk '/receiver/ {sum+=$6} END { print sum }'"
    register: receiver
  - name: Result
    tags: result
    shell: "tail -4 results/iperf*.out"
    register: result
  - name: Print Sender Stats
    tags: sender
    debug: msg="Average Sender iperf bandwidth {{ sender.stdout }} Mbits/s"
  - name: Print Receiver Stats
    tags: receiver
    debug: msg="Average Receiver iperf bandwidth {{ receiver.stdout }} Mbits/s"
  - name: Print Results
    tags: result
    debug:
      msg:
      - "Result Summary:"
      - "{{ result.stdout }}"
  - name: Create Directory and Archieve Results
    shell: "mkdir -p archieve-results && mv results/iperf*.out archieve-results/iperf*.out"
    
