- hosts: servers
  #vars_prompt:
  #- name: servers
  # prompt: "Destination IP address (Server)"
  # private: false
  tasks:
  - name: Start iperf3 Server
    shell: iperf3 --server --one-off --daemon

- hosts: clients
  vars_prompt:
  #- name: clients
  # prompt: "Source IP address (Client)"
  # private: false
  - name: bandwidth
    prompt: What is your Bandwidth in Mbps?
    private: false
  tasks:
  - name: Set iperf3 Server
    set_fact: iperf_server="{{ groups['servers'][groups['clients'].index(inventory_hostname)] }}"
  - name: set output base
    set_fact: output_base="{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}_{{ iperf_server }}.out"
  - name: Set iperf3 Out
    set_fact: iperf_out="iperf_{{ output_base }}"
  - name: start client iperf
    shell: "iperf3 -c {{ iperf_server }} 5201 --bitrate {{ bandwidth }} --bidir --time 10 >> {{ iperf_out }}"
  - name: Grab iperf Output
    fetch: src={{ iperf_out }} dest=results/ flat=yes

- hosts: localhost
  connection: local
  tasks:
  - name: Sender
    tags: sender
    shell: "tail -4 results/iperf*.out | awk '/sender/ { sum += $7; n++} END { print sum / n }'"
    register: sender
  - name: Receiver
    tags: receiver
    shell: "tail -4 results/iperf*.out | awk '/receiver/ { sum += $7; n++} END { print sum / n }'"
    register: receiver
  - name: Print Sender Stats
    tags: sender
    debug: msg="Average Sender iperf bandwidth {{ sender.stdout }} Mbits/s"
  - name: Print Receiver Stats
    tags: receiver
    debug: msg="Average Receiver iperf bandwidth {{ receiver.stdout }} Mbits/s"
  - name: Archieve Results
    shell: "mv results/iperf*.out archieve-results/iperf*.out"
