---
- hosts: "{{ servers }}"
  become: yes
  tasks:
  - name: Ensure iperf3 Server is at the latest version
    ansible.builtin.apt:
      name: iperf3
      state: latest
      install_recommends: yes
      update_cache: yes
      cache_valid_time: 3600
  - name: Start iperf3 Server
    shell: iperf3 --server --one-off --daemon

- hosts: "{{ clients }}"
  become: yes
  tasks:
  - name: Ensure iperf3 clinet is at the latest version
    ansible.builtin.apt:
      name: iperf3
      state: latest
      install_recommends: yes
      update_cache: yes
      cache_valid_time: 3600
  - name: Set iperf3 Out
    set_fact: iperf_out="iperf_results.out"
  - name: Print iperf3 server IP
    debug: msg="Iperf3 Server IP {{ servers.inventory_hostname }}"
  - name: Start iperf3 client
    shell: "iperf3 -c {{ servers.inventory_hostname }} 5201 --bitrate {{ bandwidth }} --bidir --time 10 >> {{ iperf_out }}"
  - name: Grab iperf3 Output
    fetch: src={{ iperf_out }} dest=results/ flat=yes

- hosts: localhost
  connection: local
  tasks:
  - name: Sender
    tags: sender
    shell: "tail -4 results/iperf*.out | awk '/sender/ { sum += $7; n++} END { print sum / n }'"
    register: sender
  - name: Receiver
    tags: receiver
    shell: "tail -4 results/iperf*.out | awk '/receiver/ { sum += $7; n++} END { print sum / n }'"
    register: receiver
  - name: Print Sender Stats
    tags: sender
    debug: msg="Average Sender iperf bandwidth {{ sender.stdout }} Mbits/s"
  - name: Print Receiver Stats
    tags: receiver
    debug: msg="Average Receiver iperf bandwidth {{ receiver.stdout }} Mbits/s"
  - name: Archieve Results
    shell: "mv results/iperf*.out archieve-results/iperf*.out"
